<?php  																														require_once($_SERVER['DOCUMENT_ROOT'] . "/eclipse.org-common/system/app.class.php");	require_once($_SERVER['DOCUMENT_ROOT'] . "/eclipse.org-common/system/nav.class.php"); 	require_once($_SERVER['DOCUMENT_ROOT'] . "/eclipse.org-common/system/menu.class.php"); 	$App 	= new App();	$Nav	= new Nav();	$Menu 	= new Menu();		include($App->getProjectCommon());    # All on the same line to unclutter the user's desktop'
/*******************************************************************************
 * Copyright (c) 2006 Eclipse Foundation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Wayne Beaton (Eclipse Foundation)- initial API and implementation
 *******************************************************************************/

#*****************************************************************************
#
# template.php
#
# Author: 		Wayne Beaton
# Date:			February 16, 2006
#
# Description:
#
#
#****************************************************************************

# Begin: page-specific settings.  Change these.
$pageTitle 		= "Usage Data Collector";
$pageKeywords	= "Eclipse, usage data, usagedata, cortez";
$pageAuthor		= "Wayne Beaton";

$tempdir = "./.metadata/.plugins/org.eclipse.epp.usagedata.recording";

ob_start();
?>
<link
	rel="stylesheet" type="text/css" href="layout.css" media="screen" />
<div id="maincontent">
<div id="midcolumn">

<h1><?= $pageTitle ?></h1>
<style>
.homeitem li {
	border-style: none
}
</style>

<div class="homeitem">
<h3>What does it do?</h3>
<p>The Usage Data Collector collects information about how individuals
are using the Eclipse platform. This information is periodically
uploaded to servers hosted by The Eclipse Foundation. The intent is to
use this data to help committers and organizations better understand how
developers are using Eclipse.</p>
<h4>Targeted Users of the Data:</h4>
<ul>
	<li>Users of Eclipse</li>
	<li>Committers working on Eclipse projects</li>
	<li>ISVs and organizations creating Eclipse based software</li>
	<li>Enterprise IT departments that make extensive use of Eclipse
	technology</li>
	<li>Academic researchers who want to study how developers work</li>
</ul>
<h4>Data to Be Collected</h4>
<p>Captured data is associated with a user through a combination of
workstation and workspace ids that are automatically generated by the
collector. This identification is not tied to any personal information
about the user.</p>
<p>The usage data monitors what is being used and when (timestamp),
including:</p>
<ol>
	<li>Loaded bundles</li>
	<li>Commands accessed via keyboard shortcuts</li>
	<li>Actions invoked via menus or toolbars</li>
	<li>Perspective changes</li>
	<li>View usage</li>
	<li>Editor usage</li>
</ol>
<p>Where possible, the usage data collector also capture the symbolic
name and version of the bundle contributing the
command/action/perspective/view/editor.</p>

<h4>How does it work?</h4>
<p>The Usage Data Collector is designed to have a minimal impact on user
experience. The impact on performance is negligible.</p>

<p>Once installed, the Usage Data Collector immediately starts
monitoring your use of Eclipse. In particular, it takes note of the
views, editors, perspectives, and commands that you use. It also keeps
track of when you bring the Eclipse workbench window into focus. At a
lower level, the Usage Data Collector records the bundles (plug-ins)
that are loaded by Eclipse. The information collected amounts to the id
of the entity (view, editor, perspective, etc.), the symbolic name and
version of the bundle that contains the entity, and the time of the
event.</p>

<p>We recognize that the data collected may contain sensitive
information. Symbolic names for bundles can potentially include company
and product names; bundle versions, as well as view, editor, and
perspective ids could potentially also contain sensitive information.
With this in mind, the Usage Data Collector includes a filtering
framework that can be used to restrict the type of information that is
uploaded.</p>

<p>After a configurable period of time (1 day in the beta, planned 5
days in the final) passes, it asks you for permission to upload.</p>

<p align="center"><img src="images/UploadWiz.png" /></p>

<p>At this point, you can tell the Usage Data Collector what you want to
do:</p>

<ul>
	<li><em>Upload now</em> tells the Usage Data Collector to upload the
	data that has been captured to date. After the same configurable period
	of time passes, you will be asked again.</li>

	<li><em>Upload always</em> tells the Usage Data Collector to upload the
	data that has been captured to date and not ask again. Henceforth, the
	data will be uploaded without asking.</li>

	<li><em>Don't upload</em> tells the Usage Data Collector not to upload
	the data that has been captured. After that same configurable period of
	time passes, you will be asked again. All the data collected to this
	point will be retained.</li>

	<li><em>Turn UDC feature off</em> tells the Usage Data Collector not to
	upload the data and to stop collecting the data altogether. This turns
	off the usage data collection.</li>
</ul>
<p>The period of time between requests to upload the usage data can be
configured by changing the &quot;Upload Period&quot; field on the
&quot;Usage Data Collection | Uploading&quot; preferences page.</p>

<p align="center"><img src="images/UploadingPrefs.png" /></p>

<p>The target for uploads is a server hosted by The Eclipse Foundation.
The data is stored in its collected form in a foundation database.</p>

<p>Two different keys are used to identify the source of the uploaded
data. The first key identifies the workstation; this key is stored
locally in your &quot;user home&quot; directory. The second key
identifies the workspace; this key is stored in the <em><?= $tempdir ?></em>
directory for the workspace. These keys are uploaded along with the
usage data.</p>

<p>Please review the <a href="terms.php">Terms of Use</a>.</p>
</div>

<style>
.homeitem dt {
	margin-left: 10px;
}
</style>
<div class="homeitem">

<h3>Frequently Asked Questions</h3>

<dl>
	<dt>What releases of Eclipse does the Usage Data Collector support</dt>
	<dd>
	<p>The Usage Data Collector can be installed into the Europa (Eclipse
	Top Level Project SDK 3.3.x) or Ganymede (Eclipse Top Level Project SDK
	3.4.x) Eclipse releases and milestone builds.</p>
	</dd>

	<dt>How do I install the Usage Data Collector?</dt>
	<dd>
	<p>The Usage Data Collector is included as part of the &quot;UDC&quot;
	packages produced by the EPP. An automated build process generates a
	new build that can be installed into Eclipse by pointing the update
	manager to:</p>

	<pre>http://download.eclipse.org/technology/epp/updates/testing</pre>

	<p>For more information about the build process and status, please see
	<a href="https://bugs.eclipse.org/bugs/show_bug.cgi?id=215060">Bug
	215060</a>.</p>

	<p>Integration builds are posted on the milestone update site:</p>

	<pre>http://download.eclipse.org/technology/epp/updates/1.0milestones.</pre>

	<p>The code is available in the Technology Project's CVS repository.
	Use this <a href="UsageData.psf">Team Project Set</a> to add the Usage
	Data Monitor to your workspace.</p>
	</dd>

	<dt>How do I turn off the Usage Data Collector?</dt>
	<dd>
	<p>There is an option on the &quot;Usage Data Collection&quot;
	preferences page labeled &quot;Enable Capture&quot;. Turn this option <em>off</em>.</p>
	</dd>

	<dt>Where is the information stored?</dt>
	<dd>
	<p>As the usage data is collected, it is stored locally in the <em><?= $tempdir ?></em>
	directory of the Eclipse workspace. After data has been successfully
	uploaded and the data has been transfered into the Eclipse Foundation's
	database, the local files are deleted.</p>
	</dd>

	<dt>Can I see what's been uploaded?</dt>
	<dd>
	<p>You can review some aggregations of the data that we've collected <a href="results.php">here</a>.</p>
	</dd>
</dl>
</div>
</div>

<div id="rightcolumn">
</div>
</div>
<?php
$html = ob_get_contents();
ob_end_clean();
$App->generatePage($theme, $Menu, $Nav, $pageAuthor, $pageKeywords, $pageTitle, $html);
?>